# Generated by Django 5.2.6 on 2025-09-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Description',
            field=models.TextField(default='No description available', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='available_copies',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AlterField(
            model_name='book',
            name='copies',
            field=models.PositiveIntegerField(default=90),
        ),
    ]
